using Xamarin.Forms;
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.Image), typeof(MvvmAspire.Controls.ImageControlRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.Entry), typeof(MvvmAspire.Controls.EntryControlRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.RoundedEntry), typeof(MvvmAspire.Controls.RoundedEntryRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.DatePicker), typeof(MvvmAspire.Controls.DatePickerControlRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.Picker), typeof(MvvmAspire.Controls.PickerControlRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.Editor), typeof(MvvmAspire.Controls.EditorControlRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.RoundedComboBox), typeof(MvvmAspire.Controls.RoundedComboBoxRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.ListView), typeof(MvvmAspire.Controls.ListViewRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.SearchBar), typeof(MvvmAspire.Controls.SearchBarRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.RoundedBoxView), typeof(MvvmAspire.Controls.RoundedBoxViewRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.CheckBox), typeof(MvvmAspire.Controls.CheckBoxRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.Label), typeof(MvvmAspire.Controls.LabelControlRenderer))]
[assembly: ExportRenderer (typeof(MvvmAspire.Controls.Button), typeof (MvvmAspire.Controls.ButtonControlRenderer))]
[assembly: ExportRenderer(typeof(MvvmAspire.Controls.AnimatedLabel), typeof(MvvmAspire.Controls.AnimatedLabelRenderer))]

